[viewer]
    Title = "TBGO博客"
    Description = "TB的第一个用go写的博客！！"
    Logo = "public/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/242430908"
    Zhihu = "https://www.zhihu.com"
    Avatar = "https://i2.hdslb.com/bfs/archive/3a7cf538b197a0ca1a537f27afca776f5b2f4d01.jpg@640w_400h_1c_!web-space-index-myvideo.webp"
    UserName = "TB"
    UserDesc = "博嗝儿"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "qEyOWyUFGknNfR9cIdVbVDcrsAZ6S-_0ilJzaK9a"
    QiniuSecretKey = "3uOq2tAnpCk0E31MXIa0qHb4xIDOAkZJ7Mch79sz"
    Valine = true
    ValineAppid = "wd07yN6pBuCGtvqtHrLrtqW0-gzGzoHsz"
    ValineAppkey = "Ip4aSEjGcd20sjWbuw2hKz2B"
    ValineServerURL = "https://wd07yn6p.lc-cn-n1-shared.com"